@startuml

class Simulation {
+dt
+duration
+save_every
+modeSortie
+run()
}

class Univers {
-particules
-cellules
-liste_voisins
-dim
-Lds
-r_cut
-skin
-eps
-sigma
-gravite
+ajoute_particule(p)
+initialiser_cellules()
+place_particules_dans_cellules()
+construit_liste_verlet()
+calcule_forces()
+applique_conditions_limites()
+applique_gravite()
+evolue(dt)
+energie_cinetique()
+energie_potentielle()
}

class Cellule {
-particules
-voisins
+ajoute_particule(p)
+ajoute_voisin(c)
+vide()
}

class Particule {
-id
-type
-masse
-position
-vitesse
-force
-force_old
+reset_force()
+ajouter_force(...)
+avance_position_verlet(dt)
+avance_vitesse_verlet(dt)
}

class Vecteur {
-x
-y
-z
+norme()
+norme2()
+operator+()
+operator-()
+operator*()
+operator/()
}

class IO {
+sauvegarde_txt(...)
+sauvegarde_vtk(...)
+sauvegarde_vtu(...)
+ecrire_series(...)
}

class ConditionLimite {
+appliquer(p)
}

class Reflexive
class Periodique
class Absorbante

class ErreurSimulation
class ErreurNumerique
class ErreurFichier
class ParametreInvalide

Simulation --> Univers
Simulation --> IO

Univers "1" *-- "0..*" Particule
Univers "1" *-- "1..*" Cellule

Univers --> ConditionLimite
ConditionLimite <|-- Reflexive
ConditionLimite <|-- Periodique
ConditionLimite <|-- Absorbante

Cellule --> Particule
Cellule --> Cellule

Particule --> Vecteur

IO --> Univers

ErreurSimulation <|-- ErreurNumerique
ErreurSimulation <|-- ErreurFichier
ErreurSimulation <|-- ParametreInvalide

@enduml