@startuml

actor Utilisateur
participant main
participant Univers
participant Particule
participant IO

Utilisateur -> main : lancer simulation

main -> Univers : créer univers(...)

loop initialisation
main -> Univers : ajoute_particule(p)
end

main -> Univers : initialiser_cellules()
main -> Univers : construit_liste_verlet()
main -> Univers : calcule_forces()

loop chaque pas de temps

main -> Univers : evolue(dt)

Univers -> Particule : avance_position_verlet(dt)

Univers -> Univers : applique_conditions_limites()
Univers -> Univers : place_particules_dans_cellules()

alt mise à jour Verlet
Univers -> Univers : construit_liste_verlet()
end

Univers -> Univers : calcule_forces()
Univers -> Univers : applique_gravite()

Univers -> Particule : avance_vitesse_verlet(dt)

alt sauvegarde
main -> IO : sauvegarde(...)
end

end

main -> IO : ecrire_series()
main --> Utilisateur : fin

@enduml