@startuml

[*] --> Non_initialisee

Non_initialisee --> Initialisee : création univers + particules

Initialisee --> Cellules_initialisees : init cellules
Cellules_initialisees --> Verlet_construit : construit_liste_verlet()

Verlet_construit --> Forces_calculees : calcule_forces()

Forces_calculees --> En_evolution : début boucle

En_evolution --> Position_updatee : avance_position
Position_updatee --> CL_appliquees : conditions limites
CL_appliquees --> Cellules_maj : maj cellules

Cellules_maj --> Verlet_update : si besoin
Cellules_maj --> Forces_calculees : sinon

Verlet_update --> Forces_calculees

Forces_calculees --> Vitesse_updatee : avance_vitesse

Vitesse_updatee --> Frame_sauvegardee : si save
Vitesse_updatee --> En_evolution : sinon

Frame_sauvegardee --> En_evolution

En_evolution --> Terminee : fin simulation

Terminee --> [*]

@enduml