Simulation particules Lennard-Jones: univers Class Reference
univers Class Reference
Représente l'ensemble du système physique simulé.
#include <univers.hxx>
Public Member Functions
univers ()
Constructeur par défaut.
univers (std::vector< particule * > &v, std::vector< double > Lds, double r_cut, int dim, double eps, double sigma)
Constructeur paramétré.
~univers ()
Destructeur.
void ajoute_particule (particule *p)
Ajoute une particule à l'univers.
void evolue_particules (double dt)
Fait évoluer toutes les particules sur un pas de temps.
void calcule_forces ()
Calcule les forces exercées sur toutes les particules.
void vide_cellules ()
Vide toutes les cellules de l'univers.
void place_particule_dans_cellule (particule *p)
Place une particule dans la cellule correspondant à sa position.
void place_particules_dans_cellules ()
Replace toutes les particules dans la grille de cellules.
void initialise_cellules ()
Initialise la grille de cellules et leurs relations de voisinage.
int indice_cellule (int ix, int iy=0, int iz=0) const
Calcule l'indice d'une cellule dans le tableau linéarisé.
const std::vector< particule * > & getParticules () const
Retourne l'ensemble des particules.
int getNumParticules () const
Retourne le nombre de particules.
double getRCut () const
Retourne la distance de coupure.
int getDim () const
Retourne la dimension de l'univers.
const std::vector< double > & getLds () const
Retourne les tailles du domaine.
const std::vector< int > & getNcd () const
Retourne le nombre de cellules par direction.
const std::vector< cellule > & getCellules () const
Retourne la grille des cellules.
std::vector< cellule > & getCellules ()
Retourne la grille des cellules.
void setEps (double eps)
Modifie le paramètre epsilon.
void setSigma (double sigma)
Modifie le paramètre sigma.
Detailed Description
Représente l'ensemble du système physique simulé.
L'univers contient toutes les particules ainsi qu'une grille de cellules permettant d'accélérer le calcul des interactions de Lennard-Jones.
Il stocke également les paramètres physiques et géométriques du problème :
distance de coupure,
dimension,
tailles du domaine,
nombre de cellules par direction,
paramètres du potentiel de Lennard-Jones.
Definition at line 23 of file univers.hxx.
Constructor & Destructor Documentation
univers() [1/2]
univers::univers ()
Constructeur par défaut.
Construit un univers par défaut.
Initialise un univers tridimensionnel avec :
un domaine cubique de taille 10 dans chaque direction,
une distance de coupure égale à 2.5,
des paramètres de Lennard-Jones par défaut.
La grille de cellules est ensuite initialisée.
Definition at line 14 of file univers.cxx.
References initialise_cellules().
univers() [2/2]
univers::univers (std::vector< particule * > & v, std::vector< double > Lds, double r_cut, int dim, double eps, double sigma)
Constructeur paramétré.
Construit un univers paramétré.
Parameters
v Vecteur initial de particules.
Lds Tailles du domaine.
r_cut Distance de coupure.
dim Dimension de l'univers.
eps Paramètre epsilon du potentiel de Lennard-Jones.
sigma Paramètre sigma du potentiel de Lennard-Jones.
Initialise les paramètres physiques et géométriques de l'univers, construit la grille de cellules, puis y ajoute les particules fournies.
Parameters
v Vecteur initial de particules.
Lds Tailles du domaine selon chaque direction.
r_cut Distance de coupure des interactions.
dim Dimension de l'univers.
eps Paramètre epsilon du potentiel de Lennard-Jones.
sigma Paramètre sigma du potentiel de Lennard-Jones.
Definition at line 44 of file univers.cxx.
References ajoute_particule(), and initialise_cellules().
~univers()
univers::~univers ()
Destructeur.
Détruit l'univers et libère la mémoire des particules.
Libère la mémoire des particules allouées dynamiquement.
Definition at line 88 of file univers.cxx.
Member Function Documentation
ajoute_particule()
void univers::ajoute_particule (particule * p)
Ajoute une particule à l'univers.
Ajoute une particule à l'univers en respectant sa dimension effective.
Parameters
p Pointeur vers la particule à ajouter.
Pour un univers 1D ou 2D, les composantes inutiles de position, vitesse et force sont annulées avant insertion. La particule est ensuite ajoutée à la bonne cellule.
Parameters
p Particule à ajouter.
Definition at line 135 of file univers.cxx.
References particule::getForce(), particule::getPosition(), particule::getVitesse(), place_particule_dans_cellule(), particule::setForce(), particule::setPosition(), particule::setVitesse(), vecteur::setY(), and vecteur::setZ().
Referenced by main(), and univers().
calcule_forces()
void univers::calcule_forces ()
Calcule les forces exercées sur toutes les particules.
Calcule les forces de Lennard-Jones sur toutes les particules.
Les interactions sont limitées aux particules situées dans la cellule courante et dans ses voisines, avec une coupure à la distance r_cut.
Cette implémentation exploite la décomposition spatiale en cellules afin de limiter le calcul aux paires de particules potentiellement proches.
Optimisations utilisées :
calcul uniquement avec des distances au carré,
absence de sqrt et de pow,
calcul direct sur les composantes dx, dy, dz,
application du principe action-réaction.
Les interactions sont tronquées à la distance de coupure r_cut.
La force utilisée correspond à une interaction de type Lennard-Jones.
Definition at line 368 of file univers.cxx.
References particule::ajouterForce(), particule::getPosition(), vecteur::getX(), vecteur::getY(), and vecteur::getZ().
Referenced by evolue_particules(), and main().
evolue_particules()
void univers::evolue_particules (double dt)
Fait évoluer toutes les particules sur un pas de temps.
Fait évoluer l'ensemble des particules sur un pas de temps avec Störmer-Verlet.
Parameters
dt Pas de temps.
L'évolution se fait en quatre étapes :
mise à jour des positions avec les forces actuelles,
remise à jour de la grille de cellules,
recalcul des forces,
mise à jour des vitesses.
Parameters
dt Pas de temps.
Definition at line 170 of file univers.cxx.
References calcule_forces(), and place_particules_dans_cellules().
Referenced by main().
getCellules() [1/2]
std::vector< cellule > & univers::getCellules ()
Retourne la grille des cellules.
Returns
Référence modifiable vers le vecteur des cellules.
Definition at line 123 of file univers.cxx.
getCellules() [2/2]
const std::vector< cellule > & univers::getCellules () const
Retourne la grille des cellules.
Returns
Référence constante vers le vecteur des cellules.
Definition at line 119 of file univers.cxx.
getDim()
int univers::getDim () const
Retourne la dimension de l'univers.
Returns
Dimension.
Definition at line 107 of file univers.cxx.
getLds()
const std::vector< double > & univers::getLds () const
Retourne les tailles du domaine.
Returns
Référence constante vers le vecteur des tailles.
Definition at line 111 of file univers.cxx.
getNcd()
const std::vector< int > & univers::getNcd () const
Retourne le nombre de cellules par direction.
Returns
Référence constante vers le vecteur ncd.
Definition at line 115 of file univers.cxx.
getNumParticules()
int univers::getNumParticules () const
Retourne le nombre de particules.
Returns
Nombre de particules.
Definition at line 99 of file univers.cxx.
getParticules()
const std::vector< particule * > & univers::getParticules () const
Retourne l'ensemble des particules.
Returns
Référence constante vers le vecteur de particules.
Definition at line 95 of file univers.cxx.
Referenced by operator<<(), sauvegarde_frame(), and sauvegarde_frame_vtk().
getRCut()
double univers::getRCut () const
Retourne la distance de coupure.
Returns
Valeur de r_cut.
Definition at line 103 of file univers.cxx.
indice_cellule()
int univers::indice_cellule (int ix, int iy = 0, int iz = 0) const
Calcule l'indice d'une cellule dans le tableau linéarisé.
Convertit des indices de cellule en indice linéaire dans le tableau.
Parameters
ix Indice selon x.
iy Indice selon y.
iz Indice selon z.
Returns
L'indice dans le vecteur des cellules.
Cette fonction permet de stocker une grille 1D, 2D ou 3D dans un vecteur linéaire unique.
Parameters
ix Indice selon x.
iy Indice selon y.
iz Indice selon z.
Returns
Indice de la cellule dans le vecteur cellules.
Definition at line 254 of file univers.cxx.
Referenced by initialise_cellules(), and place_particule_dans_cellule().
initialise_cellules()
void univers::initialise_cellules ()
Initialise la grille de cellules et leurs relations de voisinage.
Initialise la grille de cellules et les relations de voisinage.
Chaque cellule reçoit la liste de ses voisines immédiates. Cela permet ensuite de limiter le calcul des interactions aux particules proches dans l'espace.
Definition at line 271 of file univers.cxx.
References indice_cellule().
Referenced by univers(), and univers().
place_particule_dans_cellule()
void univers::place_particule_dans_cellule (particule * p)
Place une particule dans la cellule correspondant à sa position.
Parameters
p Pointeur vers la particule à placer.
Les indices sont bornés aux limites de la grille afin d'éviter tout débordement dans le tableau des cellules.
Parameters
p Particule à placer.
Definition at line 203 of file univers.cxx.
References particule::getPosition(), vecteur::getX(), vecteur::getY(), vecteur::getZ(), and indice_cellule().
Referenced by ajoute_particule(), and place_particules_dans_cellules().
place_particules_dans_cellules()
void univers::place_particules_dans_cellules ()
Replace toutes les particules dans la grille de cellules.
Toutes les cellules sont d'abord vidées, puis chaque particule est replacée à partir de sa position actuelle.
Definition at line 235 of file univers.cxx.
References place_particule_dans_cellule(), and vide_cellules().
Referenced by evolue_particules().
setEps()
void univers::setEps (double eps)
Modifie le paramètre epsilon.
Parameters
eps Nouvelle valeur de epsilon.
setSigma()
void univers::setSigma (double sigma)
Modifie le paramètre sigma.
Parameters
sigma Nouvelle valeur de sigma.
vide_cellules()
void univers::vide_cellules ()
Vide toutes les cellules de l'univers.
Vide toutes les cellules de la grille.
Utilisé avant de replacer les particules dans les cellules correspondant à leurs nouvelles positions.
Definition at line 189 of file univers.cxx.
Referenced by place_particules_dans_cellules().
The documentation for this class was generated from the following files:
/home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/include/univers.hxx
/home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/src/univers.cxx