Simulation particules Lennard-Jones: particule Class Reference
particule Class Reference
Représente une particule du système simulé.
#include <particule.hxx>
Public Member Functions
particule ()
Constructeur par défaut.
particule (int id, int type, double m, vecteur p, vecteur v)
Constructeur avec initialisation complète.
int getId () const
Retourne l'identifiant de la particule.
int getType () const
Retourne le type de la particule.
const vecteur & getPosition () const
Retourne la position de la particule.
const vecteur & getVitesse () const
Retourne la vitesse de la particule.
const vecteur & getForce () const
Retourne la force actuelle appliquée à la particule.
const vecteur & getForceOld () const
Retourne la force au pas précédent.
double getMasse () const
Retourne la masse de la particule.
void setForce (const vecteur &f)
Modifie la force actuelle.
void setPosition (const vecteur &p)
Modifie la position de la particule.
void setVitesse (const vecteur &v)
Modifie la vitesse de la particule.
void setForceOld (const vecteur &f)
Modifie la force au pas précédent.
void evolue (double dt)
Fait évoluer la particule sur un pas de temps.
void ajouterForce (const vecteur &f)
Ajoute une force à la force actuelle.
void ajouterForce (double fx, double fy, double fz)
Ajoute directement des composantes de force à la force actuelle.
void avance_position_verlet (double dt)
Met à jour la position avec l'étape position de Störmer-Verlet.
void avance_vitesse_verlet (double dt)
Met à jour la vitesse avec l'étape vitesse de Störmer-Verlet.
Detailed Description
Représente une particule du système simulé.
Une particule est définie par :
sa position,
sa vitesse,
la force qui s'exerce sur elle,
sa masse,
un identifiant,
un type permettant de distinguer différents ensembles de particules.
Cette classe fournit également les méthodes nécessaires à l'intégration temporelle, notamment avec l'algorithme de Störmer-Verlet.
Definition at line 23 of file particule.hxx.
Constructor & Destructor Documentation
particule() [1/2]
particule::particule ()
Constructeur par défaut.
Construit une particule nulle.
Toutes les grandeurs physiques sont initialisées à zéro. Ce constructeur est principalement utile pour créer une particule par défaut avant initialisation complète.
Definition at line 12 of file particule.cxx.
particule() [2/2]
particule::particule (int id, int type, double m, vecteur p, vecteur v)
Constructeur avec initialisation complète.
Construit une particule avec ses caractéristiques physiques initiales.
Parameters
id Identifiant de la particule.
type Type de la particule.
m Masse de la particule.
p Position initiale.
v Vitesse initiale.
Definition at line 31 of file particule.cxx.
Member Function Documentation
ajouterForce() [1/2]
void particule::ajouterForce (const vecteur & f)
Ajoute une force à la force actuelle.
Ajoute une force à la particule.
Parameters
f Force à ajouter.
Cette méthode ajoute un vecteur force à la force actuelle de la particule. Elle est moins optimisée que la version composante par composante, car elle implique la création d’un vecteur temporaire.
Parameters
f Vecteur force à ajouter.
Definition at line 122 of file particule.cxx.
Referenced by univers::calcule_forces().
ajouterForce() [2/2]
void particule::ajouterForce (double fx, double fy, double fz)
Ajoute directement des composantes de force à la force actuelle.
Ajoute directement des composantes de force à la force courante.
Parameters
fx Composante selon x.
fy Composante selon y.
fz Composante selon z.
Cette version évite la création d'un vecteur temporaire et est donc plus efficace lorsqu'elle est appelée très fréquemment dans le calcul des interactions.
Parameters
fx Composante selon x.
fy Composante selon y.
fz Composante selon z.
Definition at line 109 of file particule.cxx.
References vecteur::ajoute().
avance_position_verlet()
void particule::avance_position_verlet (double dt)
Met à jour la position avec l'étape position de Störmer-Verlet.
Met à jour la position selon la première étape de Störmer-Verlet.
Parameters
dt Pas de temps.
L'ancienne force est sauvegardée dans force_old afin d'être réutilisée lors de la mise à jour de la vitesse.
Parameters
dt Pas de temps.
Definition at line 77 of file particule.cxx.
avance_vitesse_verlet()
void particule::avance_vitesse_verlet (double dt)
Met à jour la vitesse avec l'étape vitesse de Störmer-Verlet.
Met à jour la vitesse selon la seconde étape de Störmer-Verlet.
Parameters
dt Pas de temps.
La nouvelle vitesse est calculée à partir de la moyenne entre l'ancienne force et la nouvelle force.
Parameters
dt Pas de temps.
Definition at line 92 of file particule.cxx.
evolue()
void particule::evolue (double dt)
Fait évoluer la particule sur un pas de temps.
Fait évoluer la particule sur un pas de temps avec un schéma simple.
Parameters
dt Pas de temps.
Cette méthode correspond à une évolution temporelle simple.
La vitesse est d'abord mise à jour à partir de la force actuelle, puis la position est mise à jour avec la nouvelle vitesse.
Parameters
dt Pas de temps.
Definition at line 62 of file particule.cxx.
getForce()
const vecteur & particule::getForce () const
Retourne la force actuelle appliquée à la particule.
Returns
Référence constante vers la force.
Definition at line 44 of file particule.cxx.
Referenced by univers::ajoute_particule(), and operator<<().
getForceOld()
const vecteur & particule::getForceOld () const
Retourne la force au pas précédent.
Returns
Référence constante vers l'ancienne force.
Definition at line 45 of file particule.cxx.
getId()
int particule::getId () const
Retourne l'identifiant de la particule.
Returns
L'identifiant.
Definition at line 41 of file particule.cxx.
Referenced by operator<<().
getMasse()
double particule::getMasse () const
Retourne la masse de la particule.
Returns
La masse.
Definition at line 46 of file particule.cxx.
Referenced by operator<<().
getPosition()
const vecteur & particule::getPosition () const
Retourne la position de la particule.
Returns
Référence constante vers la position.
Definition at line 42 of file particule.cxx.
Referenced by univers::ajoute_particule(), univers::calcule_forces(), operator<<(), and univers::place_particule_dans_cellule().
getType()
int particule::getType () const
Retourne le type de la particule.
Returns
Le type.
Definition at line 47 of file particule.cxx.
Referenced by operator<<().
getVitesse()
const vecteur & particule::getVitesse () const
Retourne la vitesse de la particule.
Returns
Référence constante vers la vitesse.
Definition at line 43 of file particule.cxx.
Referenced by univers::ajoute_particule(), and operator<<().
setForce()
void particule::setForce (const vecteur & f)
Modifie la force actuelle.
Parameters
f Nouvelle force.
Definition at line 49 of file particule.cxx.
Referenced by univers::ajoute_particule().
setForceOld()
void particule::setForceOld (const vecteur & f)
Modifie la force au pas précédent.
Parameters
f Nouvelle ancienne force.
Definition at line 50 of file particule.cxx.
setPosition()
void particule::setPosition (const vecteur & p)
Modifie la position de la particule.
Parameters
p Nouvelle position.
Definition at line 51 of file particule.cxx.
Referenced by univers::ajoute_particule().
setVitesse()
void particule::setVitesse (const vecteur & v)
Modifie la vitesse de la particule.
Parameters
v Nouvelle vitesse.
Definition at line 52 of file particule.cxx.
Referenced by univers::ajoute_particule().
The documentation for this class was generated from the following files:
/home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/include/particule.hxx
/home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/src/particule.cxx