Simulation particules Lennard-Jones: vecteur Class Reference
vecteur Class Reference
Représente un vecteur de dimension 3.
#include <vecteur.hxx>
Public Member Functions
vecteur ()
Constructeur par défaut.
vecteur (double x_val, double y_val, double z_val)
Constructeur avec initialisation des composantes.
double norme () const
Calcule la norme euclidienne du vecteur.
vecteur operator+ (const vecteur &other) const
Addition de deux vecteurs.
vecteur operator- (const vecteur &other) const
Soustraction de deux vecteurs.
vecteur operator* (double scalar) const
Multiplication par un scalaire.
vecteur operator/ (double scalar) const
Division par un scalaire.
double getX () const
Retourne la composante x.
double getY () const
Retourne la composante y.
double getZ () const
Retourne la composante z.
void setX (double x_val)
Modifie la composante x.
void setY (double y_val)
Modifie la composante y.
void setZ (double z_val)
Modifie la composante z.
void ajoute (double dx, double dy, double dz)
Ajoute des composantes au vecteur courant.
double norme2 () const
Calcule le carré de la norme.
double & operator[] (int index)
Accès à une composante par indice.
const double & operator[] (int index) const
Accès constant à une composante par indice.
Detailed Description
Représente un vecteur de dimension 3.
Cette classe est utilisée pour représenter les positions, vitesses et forces. Même dans une simulation 1D ou 2D, les vecteurs restent stockés avec trois composantes.
Definition at line 14 of file vecteur.hxx.
Constructor & Destructor Documentation
vecteur() [1/2]
vecteur::vecteur ()
Constructeur par défaut.
Construit un vecteur nul.
Initialise les composantes x, y et z à 0.
Definition at line 10 of file vecteur.cxx.
Referenced by operator*(), operator+(), operator-(), and operator/().
vecteur() [2/2]
vecteur::vecteur (double x_val, double y_val, double z_val)
Constructeur avec initialisation des composantes.
Construit un vecteur à partir de ses composantes.
Parameters
x_val Valeur selon x.
y_val Valeur selon y.
z_val Valeur selon z.
x_val Composante selon x.
y_val Composante selon y.
z_val Composante selon z.
Definition at line 23 of file vecteur.cxx.
Member Function Documentation
ajoute()
void vecteur::ajoute (double dx, double dy, double dz) inline
Ajoute des composantes au vecteur courant.
Parameters
dx Incrément selon x.
dy Incrément selon y.
dz Incrément selon z.
Definition at line 121 of file vecteur.hxx.
Referenced by particule::ajouterForce().
getX()
double vecteur::getX () const inline
Retourne la composante x.
Returns
La composante x.
Definition at line 83 of file vecteur.hxx.
Referenced by univers::calcule_forces(), operator<<(), and univers::place_particule_dans_cellule().
getY()
double vecteur::getY () const inline
Retourne la composante y.
Returns
La composante y.
Definition at line 89 of file vecteur.hxx.
Referenced by univers::calcule_forces(), operator<<(), and univers::place_particule_dans_cellule().
getZ()
double vecteur::getZ () const inline
Retourne la composante z.
Returns
La composante z.
Definition at line 95 of file vecteur.hxx.
Referenced by univers::calcule_forces(), operator<<(), and univers::place_particule_dans_cellule().
norme()
double vecteur::norme () const
Calcule la norme euclidienne du vecteur.
Returns
La norme du vecteur.
Definition at line 34 of file vecteur.cxx.
norme2()
double vecteur::norme2 () const inline
Calcule le carré de la norme.
Returns
La norme au carré.
Definition at line 131 of file vecteur.hxx.
operator*()
vecteur vecteur::operator* (double scalar) const
Multiplication par un scalaire.
Parameters
scalar Scalaire multiplicatif.
Returns
Le vecteur multiplié.
Parameters
scalar Facteur multiplicatif.
Returns
Nouveau vecteur résultant de la multiplication.
Definition at line 64 of file vecteur.cxx.
References vecteur().
operator+()
vecteur vecteur::operator+ (const vecteur & other) const
Addition de deux vecteurs.
Parameters
other Vecteur à additionner.
Returns
Le vecteur somme.
Parameters
other Vecteur à ajouter.
Returns
Nouveau vecteur résultant de l'addition.
Definition at line 44 of file vecteur.cxx.
References vecteur().
operator-()
vecteur vecteur::operator- (const vecteur & other) const
Soustraction de deux vecteurs.
Parameters
other Vecteur à soustraire.
Returns
Le vecteur différence.
Parameters
other Vecteur à soustraire.
Returns
Nouveau vecteur résultant de la soustraction.
Definition at line 54 of file vecteur.cxx.
References vecteur().
operator/()
vecteur vecteur::operator/ (double scalar) const
Division par un scalaire.
Parameters
scalar Scalaire diviseur.
Returns
Le vecteur divisé.
Parameters
scalar Diviseur.
Returns
Nouveau vecteur résultant de la division.
Definition at line 74 of file vecteur.cxx.
References vecteur().
operator[]() [1/2]
double & vecteur::operator[] (int index)
Accès à une composante par indice.
Accès en écriture à une composante du vecteur.
Parameters
index Indice de la composante.
Returns
Référence vers la composante demandée.
Permet de modifier directement une composante.
Parameters
index Indice (0 = x, 1 = y, 2 = z).
Returns
Référence vers la composante.
Exceptions
std::out_of_range si l'indice est invalide.
Definition at line 101 of file vecteur.cxx.
operator[]() [2/2]
const double & vecteur::operator[] (int index) const
Accès constant à une composante par indice.
Accès en lecture à une composante du vecteur.
Parameters
index Indice de la composante.
Returns
Référence constante vers la composante demandée.
Parameters
index Indice (0 = x, 1 = y, 2 = z).
Returns
Référence constante vers la composante.
Exceptions
std::out_of_range si l'indice est invalide.
Definition at line 85 of file vecteur.cxx.
setX()
void vecteur::setX (double x_val) inline
Modifie la composante x.
Parameters
x_val Nouvelle valeur.
Definition at line 101 of file vecteur.hxx.
setY()
void vecteur::setY (double y_val) inline
Modifie la composante y.
Parameters
y_val Nouvelle valeur.
Definition at line 107 of file vecteur.hxx.
Referenced by univers::ajoute_particule().
setZ()
void vecteur::setZ (double z_val) inline
Modifie la composante z.
Parameters
z_val Nouvelle valeur.
Definition at line 113 of file vecteur.hxx.
Referenced by univers::ajoute_particule().
The documentation for this class was generated from the following files:
/home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/include/vecteur.hxx
/home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/src/vecteur.cxx