Simulation particules Lennard-Jones: /home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/src/main.cxx File Reference
main.cxx File Reference
#include <iostream>
#include <vector>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <cstdlib>
#include "../include/univers.hxx"
#include "../include/io.hxx"
Macros
#define PROJECT_SOURCE_DIR "."
Functions
void sauvegarde_frame (std::ofstream &file, const univers &u, int frame_id)
void sauvegarde_frame_vtk (const univers &u, int frame_id, const std::string &dossier="vtk_frames")
void ecrire_fichier_series_json (int nb_frames, double dt, int save_every, const std::string &dossier="vtk_frames")
bool paraview_disponible ()
std::string trouver_script_python ()
int main ()
Macro Definition Documentation
PROJECT_SOURCE_DIR
#define PROJECT_SOURCE_DIR "."
Definition at line 16 of file main.cxx.
Function Documentation
ecrire_fichier_series_json()
void ecrire_fichier_series_json (int nb_frames, double dt, int save_every, const std::string & dossier = "vtk_frames")
Definition at line 74 of file main.cxx.
Referenced by main().
main()
int main ()
!!!!!!!!!!! Important: Sauvegarder chauqe les x frames !!!!!!!!!!!!!!!!!!!!!!
Definition at line 125 of file main.cxx.
References univers::ajoute_particule(), univers::calcule_forces(), ecrire_fichier_series_json(), univers::evolue_particules(), paraview_disponible(), sauvegarde_frame(), sauvegarde_frame_vtk(), and trouver_script_python().
paraview_disponible()
bool paraview_disponible ()
Definition at line 102 of file main.cxx.
Referenced by main().
sauvegarde_frame()
void sauvegarde_frame (std::ofstream & file, const univers & u, int frame_id)
Definition at line 20 of file main.cxx.
References univers::getParticules().
Referenced by main().
sauvegarde_frame_vtk()
void sauvegarde_frame_vtk (const univers & u, int frame_id, const std::string & dossier = "vtk_frames")
Definition at line 33 of file main.cxx.
References univers::getParticules().
Referenced by main().
trouver_script_python()
std::string trouver_script_python ()
Definition at line 108 of file main.cxx.
References PROJECT_SOURCE_DIR.
Referenced by main().