Simulation particules Lennard-Jones: plot_collision_3d Namespace Reference
plot_collision_3d Namespace Reference
Functions
load_frames (filename="frames_3d/frames.txt")
create_animation (df, frames)
main ()
Function Documentation
create_animation()
plot_collision_3d.create_animation (df, frames)
Crée une animation 3D de la simulation.
Les particules de type 1 et 2 sont affichées avec deux nuages
de points distincts afin de visualiser la collision ou l'évolution
des deux ensembles de particules.
Parameters
----------
df : pandas.DataFrame
    Données complètes de simulation.
frames : list
    Liste des identifiants de frame.
Returns
-------
matplotlib.animation.FuncAnimation
    Objet animation créé.
Definition at line 39 of file plot_collision_3d.py.
Referenced by main().
load_frames()
plot_collision_3d.load_frames (filename = "frames_3d/frames.txt")
Charge les données de simulation 3D depuis un fichier texte.
Le fichier doit contenir cinq colonnes :
- frame : identifiant de la frame
- x, y, z : coordonnées de la particule
- type : type de particule
Parameters
----------
filename : str
    Chemin vers le fichier de données.
Returns
-------
tuple
    df : pandas.DataFrame
        Tableau contenant toutes les particules de toutes les frames.
    frames : list
        Liste triée des identifiants de frame.
Definition at line 6 of file plot_collision_3d.py.
Referenced by main().
main()
plot_collision_3d.main ()
Point d'entrée principal du script.
Ce script charge les frames d'une simulation 3D puis affiche
une animation des particules.
Definition at line 99 of file plot_collision_3d.py.
References create_animation(), load_frames(), and main().
Referenced by main().