Simulation particules Lennard-Jones: plot_ur Namespace Reference
plot_ur Namespace Reference
Functions
load_data (filename="lj.txt")
plot_lj (r, U)
main ()
Function Documentation
load_data()
plot_ur.load_data (filename = "lj.txt")
Charge les données du potentiel de Lennard-Jones depuis un fichier.
Parameters
----------
filename : str
    Nom du fichier contenant les données (r, U(r)).
Returns
-------
tuple of np.ndarray
    r : distances
    U : potentiel associé
Raises
------
FileNotFoundError
    Si le fichier n'existe pas.
Definition at line 6 of file plot_ur.py.
Referenced by main().
main()
plot_ur.main ()
Fonction principale :
- charge les données
- trace le potentiel
Definition at line 59 of file plot_ur.py.
References load_data(), main(), and plot_lj().
Referenced by main().
plot_lj()
plot_ur.plot_lj (r, U)
Trace le potentiel de Lennard-Jones.
Parameters
----------
r : np.ndarray
    Distances
U : np.ndarray
    Valeurs du potentiel
Definition at line 33 of file plot_ur.py.
Referenced by main().