Simulation particules Lennard-Jones: plot_collision Namespace Reference
plot_collision Namespace Reference
Functions
load_frames (filename="frames/frames.txt")
create_animation (data, frame_ids)
main ()
Function Documentation
create_animation()
plot_collision.create_animation (data, frame_ids)
Crée l'animation matplotlib de la collision.
Parameters
----------
data : np.ndarray
    Données complètes de la simulation.
frame_ids : np.ndarray
    Identifiants uniques des frames.
Definition at line 44 of file plot_collision.py.
Referenced by main().
load_frames()
plot_collision.load_frames (filename = "frames/frames.txt")
Charge les données des frames de simulation depuis un fichier texte.
Le fichier doit contenir cinq colonnes :
- identifiant de frame
- x
- y
- z
- type de particule
Parameters
----------
filename : str
    Chemin vers le fichier contenant les frames.
Returns
-------
tuple
    data : np.ndarray
        Tableau contenant toutes les données.
    frame_ids : np.ndarray
        Identifiants uniques des frames.
Raises
------
FileNotFoundError
    Si le fichier n'existe pas.
Definition at line 7 of file plot_collision.py.
Referenced by main().
main()
plot_collision.main ()
Fonction principale :
- charge les données de simulation,
- crée l'animation de la collision.
Definition at line 111 of file plot_collision.py.
References create_animation(), load_frames(), and main().
Referenced by main().