Simulation particules Lennard-Jones: /home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/include/particule.hxx File Reference
particule.hxx File Reference
#include "vecteur.hxx"
#include <iostream>
#include <vector>
Classes
class particule
Représente une particule du système simulé.
Functions
std::ostream & operator<< (std::ostream &os, const particule &p)
Affichage textuel d'une particule.
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const particule & p)
Affichage textuel d'une particule.
Parameters
os Flux de sortie.
p Particule à afficher.
Returns
Le flux de sortie.
Affichage textuel d'une particule.
Parameters
os Flux de sortie.
p Particule à afficher.
Returns
Le flux de sortie.
Definition at line 133 of file particule.cxx.
References particule::getForce(), particule::getId(), particule::getMasse(), particule::getPosition(), particule::getType(), and particule::getVitesse().