Simulation particules Lennard-Jones: /home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/include/vecteur.hxx File Reference
vecteur.hxx File Reference
#include <ostream>
Classes
class vecteur
Représente un vecteur de dimension 3.
Functions
std::ostream & operator<< (std::ostream &os, const vecteur &v)
Affichage textuel d'un vecteur.
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const vecteur & v)
Affichage textuel d'un vecteur.
Parameters
os Flux de sortie.
v Vecteur à afficher.
Returns
Le flux de sortie.
Affichage textuel d'un vecteur.
Parameters
os Flux de sortie.
v Vecteur à afficher.
Returns
Le flux de sortie.
Definition at line 115 of file vecteur.cxx.
References vecteur::getX(), vecteur::getY(), and vecteur::getZ().