Simulation particules Lennard-Jones: /home/faical/Education/ENSIMAG/2A/Lessons/C++/TP4/src/vecteur.cxx File Reference
vecteur.cxx File Reference
#include "../include/vecteur.hxx"
#include <cmath>
#include <iostream>
Functions
std::ostream & operator<< (std::ostream &os, const vecteur &v)
Affiche un vecteur sous forme lisible.
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const vecteur & v)
Affiche un vecteur sous forme lisible.
Affichage textuel d'un vecteur.
Parameters
os Flux de sortie.
v Vecteur à afficher.
Returns
Le flux de sortie.
Definition at line 115 of file vecteur.cxx.
References vecteur::getX(), vecteur::getY(), and vecteur::getZ().